<form action="" method="POST" role="form"><div class="form-group "><label for="exampleInputEmail1">Email address</label><input name="input-email" type="email" placeholder="Enter&#x20;email" id="exampleInputEmail1" class="form-control" value=""></div>
<div class="form-group "><label for="exampleInputPassword1">Password</label><input name="input-password" type="password" placeholder="Password" id="exampleInputPassword1" class="form-control" value=""></div>
<div class="form-group "><label for="exampleInputFile">File input</label><input name="input-file" type="file" id="exampleInputFile"><p class="help-block">Example block-level help text here.</p></div>
<div class="checkbox"><input type="hidden" name="input-checkbox" value="0"><label><input type="checkbox" name="input-checkbox" value="1"> Check me out</label></div>
<div class="form-group "><button type="submit" name="button-submit" class="btn&#x20;btn-default" value="">Submit</button></div>
</form>