<form action="" method="POST"><div class="form-group "><input name="input-text-disabled" type="text" placeholder="Disabled input here..." id="disabledInput" class="form-control" value=""></div>
<fieldset disabled="disabled"><div class="form-group "><label for="disabledTextInput">Disabled input</label><input name="input-text-disabled" type="text" placeholder="Disabled input" id="disabledTextInput" class="form-control" value=""></div>
<div class="form-group "><label for="disabled-select">Disabled select menu</label><select name="disabled-select" id="disabled-select" class="form-control"><option value="">Disabled select</option></select></div>
<div class="checkbox"><input type="hidden" name="input-checkbox" value="0"><label><input type="checkbox" name="input-checkbox" value="1">Can't check this</label></div>
<div class="form-group "><button type="submit" name="button-submit" class="btn-primary btn" value="">Submit</button></div>
</fieldset></form>