<form method="POST" class="form-horizontal" role="form">
<div class="form-group "><div class=""><input type="text" name="input-text-1" class="form-control" value=""></div></div>
<div class="form-group "><div class="btn-group"><button type="button" name="input-button-1" class="btn&#x20;btn-default" value="">Left</button><button type="button" name="input-button-2" class="btn&#x20;btn-default" value="">Right</button></div></div>
<div class="form-group "><div class="btn-group"><button type="button" name="input-button-3" class="btn&#x20;btn-default" value="">Left</button><button type="button" name="input-button-4" class="btn&#x20;btn-default" value="">Right</button></div></div>
<div class="form-group "><div class=""><input type="text" name="input-text-3" class="form-control" value=""></div></div>
</form>