<form action="" method="POST" role="form"><div class="form-group "><input name="input-text-lg" type="text" placeholder=".input-lg" class="input-lg form-control" value=""></div>
<div class="form-group "><input name="input-text-default" type="text" placeholder="Default input" class="form-control" value=""></div>
<div class="form-group "><input name="input-text-sm" type="text" placeholder=".input-sm" class="input-sm form-control" value=""></div>
<div class="form-group "><select name="lg-select" class="input-lg form-control"><option value="">.input-lg</option></select></div>
<div class="form-group "><select name="default-select" class="form-control"><option value="">Default select</option></select></div>
<div class="form-group "><select name="sm-select" class="input-sm form-control"><option value="">.input-sm</option></select></div>
</form>