<form action="" method="POST" class="form-inline" role="form"><div class="row"><div class="form-group  col-lg-2"><input name="input-text-col-lg-2" type="text" placeholder=".col-lg-2" class="form-control" value=""></div>
<div class="form-group  col-lg-3"><input name="input-text-col-lg-3" type="text" placeholder=".col-lg-3" class="form-control" value=""></div>
<div class="form-group  col-lg-4"><input name="input-text-col-lg-4" type="text" placeholder=".col-lg-4" class="form-control" value=""></div>
</div></form>