<form action="" method="POST" class="form-inline" role="form"><div class="form-group "><label class="sr-only" for="exampleInputEmail2">Email address</label><input name="input-email" type="email" placeholder="Enter&#x20;email" id="exampleInputEmail2" class="form-control" value=""></div>
<div class="form-group "><label class="sr-only" for="exampleInputPassword2">Password</label><input name="input-password" type="password" placeholder="Password" id="exampleInputPassword2" class="form-control" value=""></div>
<div class="checkbox"><input type="hidden" name="input-checkbox" value="0"><label><input type="checkbox" name="input-checkbox" value="1"> Remember me</label></div>
<button type="submit" name="button-submit" class="btn&#x20;btn-default" value="">Sign in</button>
</form>