<form action="" method="POST" role="form"><div class="form-group "><input name="input-text" type="text" placeholder="Text&#x20;input" class="form-control" value=""></div>
<div class="form-group "><textarea name="input-text-area" class="form-control"></textarea></div>
<div class="checkbox"><input type="hidden" name="input-checkbox" value="0"><label><input type="checkbox" name="input-checkbox" value="1"> Option one is this and that-be sure to include why it's great</label></div>
<div class="form-group "><div class="radio"><label><input type="radio" name="optionsRadios" value="option1">Option one is this and that-be sure to include why it&#039;s great</label></div><div class="radio"><label><input type="radio" name="optionsRadios" value="optionsRadios2">Option two can be something else and selecting it will deselect option one</label></div></div>
<div class="form-group "><label class="checkbox-inline"><input type="checkbox" name="optionsRadios&#x5B;&#x5D;" id="inlineCheckbox1" value="option1">1</label><label class="checkbox-inline"><input type="checkbox" name="optionsRadios&#x5B;&#x5D;" id="inlineCheckbox2" value="option2">2</label><label class="checkbox-inline"><input type="checkbox" name="optionsRadios&#x5B;&#x5D;" id="inlineCheckbox3" value="option3">3</label></div>
<div class="form-group "><div class="checkbox"><label class="checkbox"><input type="checkbox" name="optionsRadiosNoInline&#x5B;&#x5D;" id="noInlineCheckbox1" value="option1">1</label></div><div class="checkbox"><label class="checkbox"><input type="checkbox" name="optionsRadiosNoInline&#x5B;&#x5D;" id="noInlineCheckbox2" value="option2">2</label></div><div class="checkbox"><label class="checkbox"><input type="checkbox" name="optionsRadiosNoInline&#x5B;&#x5D;" id="noInlineCheckbox3" value="option3">3</label></div></div>
<div class="form-group "><select name="select" class="form-control"><option value="0">1</option>
<option value="1">2</option>
<option value="2">3</option>
<option value="3">4</option>
<option value="4">5</option></select></div>
<div class="form-group "><select name="multiple-select&#x5B;&#x5D;" multiple="multiple" class="form-control"><option value="0">1</option>
<option value="1">2</option>
<option value="2">3</option>
<option value="3">4</option>
<option value="4">5</option></select></div>
</form>