<div class="alert-success&#x20;alert"><strong>Well done!</strong> You successfully read this important alert message.</div>
<div class="alert-info&#x20;alert"><strong>Heads up!</strong> This alert needs your attention, but it's not super important.</div>
<div class="alert-warning&#x20;alert"><strong>Warning!</strong> Best check yo self, you're not looking too good.</div>
<div class="alert-danger&#x20;alert"><strong>Oh snap!</strong> Change a few things up and try submitting again.</div>
