<div class="input-group "><span class="input-group-btn"><button type="button" name="append-button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" value="">Action <b class="caret"></b></button><ul class="dropdown-menu"><li ><a href="#" tabindex="-1">Action</a></li>
<li ><a href="#" tabindex="-1">Another action</a></li>
<li ><a href="#" tabindex="-1">Something else here</a></li>
<li class="divider"></li>
<li ><a href="#" tabindex="-1">Separated link</a></li>
</ul></span><input type="text" name="input-username" class="form-control" value=""></div>
<div class="input-group "><input type="text" name="input-username" class="form-control" value=""><span class="input-group-btn"><button type="button" name="prepend-button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" value="">Action <b class="caret"></b></button><ul class="dropdown-menu"><li ><a href="#" tabindex="-1">Action</a></li>
<li ><a href="#" tabindex="-1">Another action</a></li>
<li ><a href="#" tabindex="-1">Something else here</a></li>
<li class="divider"></li>
<li ><a href="#" tabindex="-1">Separated link</a></li>
</ul></span></div>
