<div class="alert-success alert"><strong>Well done!</strong> You successfully read this important alert message.</div>
<div class="alert-info alert"><strong>Heads up!</strong> This alert needs your attention, but it's not super important.</div>
<div class="alert-warning alert"><strong>Warning!</strong> Best check yo self, you're not looking too good.</div>
<div class="alert-danger alert"><strong>Oh snap!</strong> Change a few things up and try submitting again.</div>
