<button type="button" name="align-left" class="btn btn-default" value=""><span class="glyphicon glyphicon-align-left"></span></button>
<button type="button" name="align-left" class="btn btn-default" value=""><span class="glyphicon glyphicon-align-center"></span></button>
<button type="button" name="align-left" class="btn btn-default" value=""><span class="glyphicon glyphicon-align-right"></span></button>
<button type="button" name="large-button-default" class="btn-lg btn btn-default" value=""><span class="glyphicon glyphicon-star"></span> Star</button>
<button type="button" name="button-default" class="btn btn-default" value=""><span class="glyphicon glyphicon-star"></span> Star</button>
<button type="button" name="small-button-default" class="btn-sm btn btn-default" value=""><span class="glyphicon glyphicon-star"></span> Star</button>
<button type="button" name="extra-small-button-default" class="btn-xs btn btn-default" value=""><span class="glyphicon glyphicon-star"></span> Star</button>
