<button type="button" name="align-left" class="btn&#x20;btn-default" value=""><span class="glyphicon&#x20;glyphicon-align-left"></span></button>
<button type="button" name="align-left" class="btn&#x20;btn-default" value=""><span class="glyphicon&#x20;glyphicon-align-center"></span></button>
<button type="button" name="align-left" class="btn&#x20;btn-default" value=""><span class="glyphicon&#x20;glyphicon-align-right"></span></button>
<button type="button" name="large-button-default" class="btn-lg&#x20;btn&#x20;btn-default" value=""><span class="glyphicon&#x20;glyphicon-star"></span> Star</button>
<button type="button" name="button-default" class="btn&#x20;btn-default" value=""><span class="glyphicon&#x20;glyphicon-star"></span> Star</button>
<button type="button" name="small-button-default" class="btn-sm&#x20;btn&#x20;btn-default" value=""><span class="glyphicon&#x20;glyphicon-star"></span> Star</button>
<button type="button" name="extra-small-button-default" class="btn-xs&#x20;btn&#x20;btn-default" value=""><span class="glyphicon&#x20;glyphicon-star"></span> Star</button>
