<button type="button" name="default" class="btn btn-default" value="">Default</button>
<button type="button" name="primary" class="btn-primary btn" value="">Primary</button>
<button type="button" name="success" class="btn-success btn" value="">Success</button>
<button type="button" name="info" class="btn-info btn" value="">Info</button>
<button type="button" name="warning" class="btn-warning btn" value="">Warning</button>
<button type="button" name="danger" class="btn-danger btn" value="">Danger</button>
<button type="button" name="link" class="btn-link btn btn-default" value="">Link</button>
