<button type="button" name="large-button-primary" class="btn-primary btn-lg btn" value="">Large button</button>
<button type="button" name="large-button-default" class="btn-lg btn btn-default" value="">Large button</button>
<button type="button" name="button-primary" class="btn-primary btn" value="">Default button</button>
<button type="button" name="button-default" class="btn btn-default" value="">Default button</button>
<button type="button" name="small-button-primary" class="btn-primary btn-sm btn" value="">Small button</button>
<button type="button" name="small-button-default" class="btn-sm btn btn-default" value="">Small button</button>
<button type="button" name="extra-small-button-primary" class="btn-primary btn-xs btn" value="">Extra small button</button>
<button type="button" name="extra-small-button-default" class="btn-xs btn btn-default" value="">Extra small button</button>
<button type="button" name="block-level-button-primary" class="btn-primary btn-block btn" value="">Block level button</button>
<button type="button" name="block-level-button-default" class="btn-block btn btn-default" value="">Block level button</button>
