<div class="input-group "><span class="input-group-addon">@</span><input type="text" name="input-prepend" placeholder="Username" class="form-control" value=""></div>
<div class="input-group "><input type="text" name="input-append" class="form-control" value=""><span class="input-group-addon">.00</span></div>
<div class="input-group "><span class="input-group-addon">$</span><input type="text" name="input-append-prepend" class="form-control" value=""><span class="input-group-addon">.00</span></div>
