<div class="input-group "><div class="input-group-btn"><button type="button" name="prepend-button" class="btn&#x20;btn-default&#x20;dropdown-toggle" data-toggle="dropdown" value="">Action <b class="caret"></b></button><ul class="dropdown-menu" role="menu"><li role="presentation"><a href="&#x23;" role="menuitem" tabindex="-1">Action</a></li>
<li role="presentation"><a href="&#x23;" role="menuitem" tabindex="-1">Another action</a></li>
<li role="presentation"><a href="&#x23;" role="menuitem" tabindex="-1">Something else here</a></li>
<li role="presentation" class="divider"></li>
<li role="presentation"><a href="&#x23;" role="menuitem" tabindex="-1">Separated link</a></li>
</ul></div><input type="text" name="input-username" class="form-control" value=""></div>
<div class="input-group "><input type="text" name="input-username" class="form-control" value=""><div class="input-group-btn"><button type="button" name="append-button" class="btn&#x20;btn-default&#x20;dropdown-toggle" data-toggle="dropdown" value="">Action <b class="caret"></b></button><ul class="dropdown-menu" role="menu"><li role="presentation"><a href="&#x23;" role="menuitem" tabindex="-1">Action</a></li>
<li role="presentation"><a href="&#x23;" role="menuitem" tabindex="-1">Another action</a></li>
<li role="presentation"><a href="&#x23;" role="menuitem" tabindex="-1">Something else here</a></li>
<li role="presentation" class="divider"></li>
<li role="presentation"><a href="&#x23;" role="menuitem" tabindex="-1">Separated link</a></li>
</ul></div></div>
