<div class="input-group input-group-lg"><span class="input-group-addon">@</span><input type="text" name="input-username" placeholder="Username" class="input-lg form-control" value=""></div>
<div class="input-group "><span class="input-group-addon">@</span><input type="text" name="input-username" placeholder="Username" class="form-control" value=""></div>
<div class="input-group input-group-sm"><span class="input-group-addon">@</span><input type="text" name="input-username" placeholder="Username" class="input-sm form-control" value=""></div>
