<div class="input-group input-group-lg"><span class="input-group-addon">@</span><input type="text" name="input-prepend" placeholder="Username" class="input-lg&#x20;form-control" value=""></div>
<div class="input-group "><span class="input-group-addon">@</span><input type="text" name="input-prepend" placeholder="Username" class="form-control" value=""></div>
<div class="input-group input-group-sm"><span class="input-group-addon">@</span><input type="text" name="input-prepend" placeholder="Username" class="input-sm&#x20;form-control" value=""></div>
