<button type="button" name="default" class="btn&#x20;btn-default" value="">Default</button>
<button type="button" name="primary" class="btn-primary&#x20;btn" value="">Primary</button>
<button type="button" name="success" class="btn-success&#x20;btn" value="">Success</button>
<button type="button" name="info" class="btn-info&#x20;btn" value="">Info</button>
<button type="button" name="warning" class="btn-warning&#x20;btn" value="">Warning</button>
<button type="button" name="danger" class="btn-danger&#x20;btn" value="">Danger</button>
<button type="button" name="link" class="btn-link&#x20;btn&#x20;btn-default" value="">Link</button>
