<button type="button" name="large-button-primary" class="btn-primary&#x20;btn-lg&#x20;btn" value="">Large button</button>
<button type="button" name="large-button-default" class="btn-lg&#x20;btn&#x20;btn-default" value="">Large button</button>
<button type="button" name="button-primary" class="btn-primary&#x20;btn" value="">Default button</button>
<button type="button" name="button-default" class="btn&#x20;btn-default" value="">Default button</button>
<button type="button" name="small-button-primary" class="btn-primary&#x20;btn-sm&#x20;btn" value="">Small button</button>
<button type="button" name="small-button-default" class="btn-sm&#x20;btn&#x20;btn-default" value="">Small button</button>
<button type="button" name="extra-small-button-primary" class="btn-primary&#x20;btn-xs&#x20;btn" value="">Extra small button</button>
<button type="button" name="extra-small-button-default" class="btn-xs&#x20;btn&#x20;btn-default" value="">Extra small button</button>
<button type="button" name="block-level-button-primary" class="btn-primary&#x20;btn-block&#x20;btn" value="">Block level button</button>
<button type="button" name="block-level-button-default" class="btn-block&#x20;btn&#x20;btn-default" value="">Block level button</button>
