<div class="clearfix dropdown"><a class="sr-only dropdown-toggle" data-toggle="dropdown" role="button" href="#" id="dropdownMenu1">Dropdown <b class="caret"></b></a><ul class="pull-right dropdown-menu" role="menu"><li role="presentation"><a href="#" role="menuitem" tabindex="-1">Action</a></li>
<li role="presentation"><a href="#" role="menuitem" tabindex="-1">Another action</a></li>
<li role="presentation"><a href="#" role="menuitem" tabindex="-1">Something else here</a></li>
<li role="presentation" class="divider"></li>
<li role="presentation"><a href="#" role="menuitem" tabindex="-1">Separated link</a></li>
</ul></div>