<div class="clearfix&#x20;dropdown"><a class="sr-only&#x20;dropdown-toggle" data-toggle="dropdown" role="button" href="&#x23;" id="dropdownMenu1">Dropdown <b class="caret"></b></a><ul class="pull-right&#x20;dropdown-menu" role="menu"><li role="presentation"><a href="&#x23;" role="menuitem" tabindex="-1">Action</a></li>
<li role="presentation"><a href="&#x23;" role="menuitem" tabindex="-1">Another action</a></li>
<li role="presentation"><a href="&#x23;" role="menuitem" tabindex="-1">Something else here</a></li>
<li role="presentation" class="divider"></li>
<li role="presentation"><a href="&#x23;" role="menuitem" tabindex="-1">Separated link</a></li>
</ul></div>