<div class="clearfix dropdown"><a class="sr-only dropdown-toggle" data-toggle="dropdown" role="button" href="#" id="dropdownMenu1">Dropdown <b class="caret"></b></a><ul class="dropdown-menu" role="menu"><li role="presentation"><a href="#" role="menuitem" tabindex="-1">Regular link</a></li>
<li class="disabled" role="presentation"><a role="menuitem" tabindex="-1" href="#">Disabled link</a></li>
<li role="presentation"><a href="#" role="menuitem" tabindex="-1">Another link</a></li>
</ul></div>