<div class="clearfix&#x20;dropdown"><a class="sr-only&#x20;dropdown-toggle" data-toggle="dropdown" role="button" href="&#x23;" id="dropdownMenu1">Dropdown <b class="caret"></b></a><ul class="dropdown-menu" role="menu"><li role="presentation"><a href="&#x23;" role="menuitem" tabindex="-1">Regular link</a></li>
<li class="disabled" role="presentation"><a role="menuitem" tabindex="-1" href="&#x23;">Disabled link</a></li>
<li role="presentation"><a href="&#x23;" role="menuitem" tabindex="-1">Another link</a></li>
</ul></div>