<div class="clearfix dropdown"><a class="sr-only dropdown-toggle" data-toggle="dropdown" href="#" id="dropdownMenu1">Dropdown <b class="caret"></b></a><ul class="dropdown-menu"><li class="dropdown-header">Dropdown header</li>
<li ><a href="#" tabindex="-1">Action</a></li>
<li ><a href="#" tabindex="-1">Another action</a></li>
<li ><a href="#" tabindex="-1">Something else here</a></li>
<li class="divider"></li>
<li class="dropdown-header">Dropdown header</li>
<li ><a href="#" tabindex="-1">Separated link</a></li>
</ul></div>