<div class="btn-group "><button type="button" name="default" class="btn&#x20;btn-default&#x20;dropdown-toggle" data-toggle="dropdown" value="">Default <b class="caret"></b></button><ul class="dropdown-menu" role="menu"><li role="presentation"><a href="&#x23;" role="menuitem" tabindex="-1">Action</a></li>
<li role="presentation"><a href="&#x23;" role="menuitem" tabindex="-1">Another action</a></li>
<li role="presentation"><a href="&#x23;" role="menuitem" tabindex="-1">Something else here</a></li>
<li role="presentation" class="divider"></li>
<li role="presentation"><a href="&#x23;" role="menuitem" tabindex="-1">Separated link</a></li>
</ul></div>
<div class="btn-group "><button type="button" name="primary" class="btn-primary&#x20;btn&#x20;dropdown-toggle" data-toggle="dropdown" value="">Primary <b class="caret"></b></button><ul class="dropdown-menu" role="menu"><li role="presentation"><a href="&#x23;" role="menuitem" tabindex="-1">Action</a></li>
<li role="presentation"><a href="&#x23;" role="menuitem" tabindex="-1">Another action</a></li>
<li role="presentation"><a href="&#x23;" role="menuitem" tabindex="-1">Something else here</a></li>
<li role="presentation" class="divider"></li>
<li role="presentation"><a href="&#x23;" role="menuitem" tabindex="-1">Separated link</a></li>
</ul></div>
<div class="btn-group "><button type="button" name="success" class="btn-success&#x20;btn&#x20;dropdown-toggle" data-toggle="dropdown" value="">Success <b class="caret"></b></button><ul class="dropdown-menu" role="menu"><li role="presentation"><a href="&#x23;" role="menuitem" tabindex="-1">Action</a></li>
<li role="presentation"><a href="&#x23;" role="menuitem" tabindex="-1">Another action</a></li>
<li role="presentation"><a href="&#x23;" role="menuitem" tabindex="-1">Something else here</a></li>
<li role="presentation" class="divider"></li>
<li role="presentation"><a href="&#x23;" role="menuitem" tabindex="-1">Separated link</a></li>
</ul></div>
<div class="btn-group "><button type="button" name="info" class="btn-info&#x20;btn&#x20;dropdown-toggle" data-toggle="dropdown" value="">Info <b class="caret"></b></button><ul class="dropdown-menu" role="menu"><li role="presentation"><a href="&#x23;" role="menuitem" tabindex="-1">Action</a></li>
<li role="presentation"><a href="&#x23;" role="menuitem" tabindex="-1">Another action</a></li>
<li role="presentation"><a href="&#x23;" role="menuitem" tabindex="-1">Something else here</a></li>
<li role="presentation" class="divider"></li>
<li role="presentation"><a href="&#x23;" role="menuitem" tabindex="-1">Separated link</a></li>
</ul></div>
<div class="btn-group "><button type="button" name="warning" class="btn-warning&#x20;btn&#x20;dropdown-toggle" data-toggle="dropdown" value="">Warning <b class="caret"></b></button><ul class="dropdown-menu" role="menu"><li role="presentation"><a href="&#x23;" role="menuitem" tabindex="-1">Action</a></li>
<li role="presentation"><a href="&#x23;" role="menuitem" tabindex="-1">Another action</a></li>
<li role="presentation"><a href="&#x23;" role="menuitem" tabindex="-1">Something else here</a></li>
<li role="presentation" class="divider"></li>
<li role="presentation"><a href="&#x23;" role="menuitem" tabindex="-1">Separated link</a></li>
</ul></div>
<div class="btn-group "><button type="button" name="danger" class="btn-danger&#x20;btn&#x20;dropdown-toggle" data-toggle="dropdown" value="">Danger <b class="caret"></b></button><ul class="dropdown-menu" role="menu"><li role="presentation"><a href="&#x23;" role="menuitem" tabindex="-1">Action</a></li>
<li role="presentation"><a href="&#x23;" role="menuitem" tabindex="-1">Another action</a></li>
<li role="presentation"><a href="&#x23;" role="menuitem" tabindex="-1">Something else here</a></li>
<li role="presentation" class="divider"></li>
<li role="presentation"><a href="&#x23;" role="menuitem" tabindex="-1">Separated link</a></li>
</ul></div>
