<div class="btn-group dropup"><button type="button" name="default" class="btn btn-default" value="">Dropup</button><button type="button" class="dropdown-toggle btn btn-default" data-toggle="dropdown"><span class="caret"></span></button><ul class="dropdown-menu" role="menu"><li role="presentation"><a href="#" role="menuitem" tabindex="-1">Action</a></li>
<li role="presentation"><a href="#" role="menuitem" tabindex="-1">Another action</a></li>
<li role="presentation"><a href="#" role="menuitem" tabindex="-1">Something else here</a></li>
<li role="presentation" class="divider"></li>
<li role="presentation"><a href="#" role="menuitem" tabindex="-1">Separated link</a></li>
</ul></div>
<div class="btn-group dropup"><button type="button" name="primary" class="btn-primary btn" value="">Right dropup</button><button type="button" class="dropdown-toggle btn-primary btn" data-toggle="dropdown"><span class="caret"></span></button><ul class="pull-right dropdown-menu" role="menu"><li role="presentation"><a href="#" role="menuitem" tabindex="-1">Action</a></li>
<li role="presentation"><a href="#" role="menuitem" tabindex="-1">Another action</a></li>
<li role="presentation"><a href="#" role="menuitem" tabindex="-1">Something else here</a></li>
<li role="presentation" class="divider"></li>
<li role="presentation"><a href="#" role="menuitem" tabindex="-1">Separated link</a></li>
</ul></div>
