<div class="btn-group "><button type="button" name="large-button-default" class="btn-lg btn btn-default dropdown-toggle" data-toggle="dropdown" value="">Large button <b class="caret"></b></button><ul class="dropdown-menu" role="menu"><li role="presentation"><a href="#" role="menuitem" tabindex="-1">Action</a></li>
<li role="presentation"><a href="#" role="menuitem" tabindex="-1">Another action</a></li>
<li role="presentation"><a href="#" role="menuitem" tabindex="-1">Something else here</a></li>
<li role="presentation" class="divider"></li>
<li role="presentation"><a href="#" role="menuitem" tabindex="-1">Separated link</a></li>
</ul></div>
<div class="btn-group "><button type="button" name="small-button-default" class="btn-sm btn btn-default dropdown-toggle" data-toggle="dropdown" value="">Small button <b class="caret"></b></button><ul class="dropdown-menu" role="menu"><li role="presentation"><a href="#" role="menuitem" tabindex="-1">Action</a></li>
<li role="presentation"><a href="#" role="menuitem" tabindex="-1">Another action</a></li>
<li role="presentation"><a href="#" role="menuitem" tabindex="-1">Something else here</a></li>
<li role="presentation" class="divider"></li>
<li role="presentation"><a href="#" role="menuitem" tabindex="-1">Separated link</a></li>
</ul></div>
<div class="btn-group "><button type="button" name="extra-small-button-default" class="btn-xs btn btn-default dropdown-toggle" data-toggle="dropdown" value="">Extra small button <b class="caret"></b></button><ul class="dropdown-menu" role="menu"><li role="presentation"><a href="#" role="menuitem" tabindex="-1">Action</a></li>
<li role="presentation"><a href="#" role="menuitem" tabindex="-1">Another action</a></li>
<li role="presentation"><a href="#" role="menuitem" tabindex="-1">Something else here</a></li>
<li role="presentation" class="divider"></li>
<li role="presentation"><a href="#" role="menuitem" tabindex="-1">Separated link</a></li>
</ul></div>
