<div class="btn-group "><button type="button" name="default" class="btn btn-default dropdown-toggle" data-toggle="dropdown" value="">Default <b class="caret"></b></button><ul class="dropdown-menu"><li ><a href="#" tabindex="-1">Action</a></li>
<li ><a href="#" tabindex="-1">Another action</a></li>
<li ><a href="#" tabindex="-1">Something else here</a></li>
<li class="divider"></li>
<li ><a href="#" tabindex="-1">Separated link</a></li>
</ul></div>
<div class="btn-group "><button type="button" name="primary" class="btn-primary btn dropdown-toggle" data-toggle="dropdown" value="">Primary <b class="caret"></b></button><ul class="dropdown-menu"><li ><a href="#" tabindex="-1">Action</a></li>
<li ><a href="#" tabindex="-1">Another action</a></li>
<li ><a href="#" tabindex="-1">Something else here</a></li>
<li class="divider"></li>
<li ><a href="#" tabindex="-1">Separated link</a></li>
</ul></div>
<div class="btn-group "><button type="button" name="success" class="btn-success btn dropdown-toggle" data-toggle="dropdown" value="">Success <b class="caret"></b></button><ul class="dropdown-menu"><li ><a href="#" tabindex="-1">Action</a></li>
<li ><a href="#" tabindex="-1">Another action</a></li>
<li ><a href="#" tabindex="-1">Something else here</a></li>
<li class="divider"></li>
<li ><a href="#" tabindex="-1">Separated link</a></li>
</ul></div>
<div class="btn-group "><button type="button" name="info" class="btn-info btn dropdown-toggle" data-toggle="dropdown" value="">Info <b class="caret"></b></button><ul class="dropdown-menu"><li ><a href="#" tabindex="-1">Action</a></li>
<li ><a href="#" tabindex="-1">Another action</a></li>
<li ><a href="#" tabindex="-1">Something else here</a></li>
<li class="divider"></li>
<li ><a href="#" tabindex="-1">Separated link</a></li>
</ul></div>
<div class="btn-group "><button type="button" name="warning" class="btn-warning btn dropdown-toggle" data-toggle="dropdown" value="">Warning <b class="caret"></b></button><ul class="dropdown-menu"><li ><a href="#" tabindex="-1">Action</a></li>
<li ><a href="#" tabindex="-1">Another action</a></li>
<li ><a href="#" tabindex="-1">Something else here</a></li>
<li class="divider"></li>
<li ><a href="#" tabindex="-1">Separated link</a></li>
</ul></div>
<div class="btn-group "><button type="button" name="danger" class="btn-danger btn dropdown-toggle" data-toggle="dropdown" value="">Danger <b class="caret"></b></button><ul class="dropdown-menu"><li ><a href="#" tabindex="-1">Action</a></li>
<li ><a href="#" tabindex="-1">Another action</a></li>
<li ><a href="#" tabindex="-1">Something else here</a></li>
<li class="divider"></li>
<li ><a href="#" tabindex="-1">Separated link</a></li>
</ul></div>
