<div class="btn-group "><button type="button" name="default" class="btn&#x20;btn-default" value="">Default</button><button type="button" class="dropdown-toggle btn btn-default" data-toggle="dropdown"><span class="caret"></span></button><ul class="dropdown-menu" role="menu"><li role="presentation"><a href="&#x23;" role="menuitem" tabindex="-1">Action</a></li>
<li role="presentation"><a href="&#x23;" role="menuitem" tabindex="-1">Another action</a></li>
<li role="presentation"><a href="&#x23;" role="menuitem" tabindex="-1">Something else here</a></li>
<li role="presentation" class="divider"></li>
<li role="presentation"><a href="&#x23;" role="menuitem" tabindex="-1">Separated link</a></li>
</ul></div>
<div class="btn-group "><button type="button" name="primary" class="btn-primary&#x20;btn" value="">Primary</button><button type="button" class="dropdown-toggle btn-primary btn" data-toggle="dropdown"><span class="caret"></span></button><ul class="dropdown-menu" role="menu"><li role="presentation"><a href="&#x23;" role="menuitem" tabindex="-1">Action</a></li>
<li role="presentation"><a href="&#x23;" role="menuitem" tabindex="-1">Another action</a></li>
<li role="presentation"><a href="&#x23;" role="menuitem" tabindex="-1">Something else here</a></li>
<li role="presentation" class="divider"></li>
<li role="presentation"><a href="&#x23;" role="menuitem" tabindex="-1">Separated link</a></li>
</ul></div>
<div class="btn-group "><button type="button" name="success" class="btn-success&#x20;btn" value="">Success</button><button type="button" class="dropdown-toggle btn-success btn" data-toggle="dropdown"><span class="caret"></span></button><ul class="dropdown-menu" role="menu"><li role="presentation"><a href="&#x23;" role="menuitem" tabindex="-1">Action</a></li>
<li role="presentation"><a href="&#x23;" role="menuitem" tabindex="-1">Another action</a></li>
<li role="presentation"><a href="&#x23;" role="menuitem" tabindex="-1">Something else here</a></li>
<li role="presentation" class="divider"></li>
<li role="presentation"><a href="&#x23;" role="menuitem" tabindex="-1">Separated link</a></li>
</ul></div>
<div class="btn-group "><button type="button" name="info" class="btn-info&#x20;btn" value="">Info</button><button type="button" class="dropdown-toggle btn-info btn" data-toggle="dropdown"><span class="caret"></span></button><ul class="dropdown-menu" role="menu"><li role="presentation"><a href="&#x23;" role="menuitem" tabindex="-1">Action</a></li>
<li role="presentation"><a href="&#x23;" role="menuitem" tabindex="-1">Another action</a></li>
<li role="presentation"><a href="&#x23;" role="menuitem" tabindex="-1">Something else here</a></li>
<li role="presentation" class="divider"></li>
<li role="presentation"><a href="&#x23;" role="menuitem" tabindex="-1">Separated link</a></li>
</ul></div>
<div class="btn-group "><button type="button" name="warning" class="btn-warning&#x20;btn" value="">Warning</button><button type="button" class="dropdown-toggle btn-warning btn" data-toggle="dropdown"><span class="caret"></span></button><ul class="dropdown-menu" role="menu"><li role="presentation"><a href="&#x23;" role="menuitem" tabindex="-1">Action</a></li>
<li role="presentation"><a href="&#x23;" role="menuitem" tabindex="-1">Another action</a></li>
<li role="presentation"><a href="&#x23;" role="menuitem" tabindex="-1">Something else here</a></li>
<li role="presentation" class="divider"></li>
<li role="presentation"><a href="&#x23;" role="menuitem" tabindex="-1">Separated link</a></li>
</ul></div>
<div class="btn-group "><button type="button" name="danger" class="btn-danger&#x20;btn" value="">Danger</button><button type="button" class="dropdown-toggle btn-danger btn" data-toggle="dropdown"><span class="caret"></span></button><ul class="dropdown-menu" role="menu"><li role="presentation"><a href="&#x23;" role="menuitem" tabindex="-1">Action</a></li>
<li role="presentation"><a href="&#x23;" role="menuitem" tabindex="-1">Another action</a></li>
<li role="presentation"><a href="&#x23;" role="menuitem" tabindex="-1">Something else here</a></li>
<li role="presentation" class="divider"></li>
<li role="presentation"><a href="&#x23;" role="menuitem" tabindex="-1">Separated link</a></li>
</ul></div>
